### ISSUE TITLE
"Sorry, you have to provide the node/bash binary path manually in the params" when using addEventListener

### ISSUE THREAD

**Issue by warrenmcquinn** [Worie/btt#29] opened 2019-01-08 17:30 UTC
Hey there Worie - this is an awesome library, and you're doing a great job! I'm trying to set up `btt-node-server` alongside this library, and I'm running into some issues. 

First of all, I can instantiate `btt`  (which I've installed within a local Create React App) in the browser and execute triggers in BTT. It's awesome.

However, when I attempt to use `btt.addEventListener` to access `btt-node-server`, an error prints in my console:

`Sorry, you have to provide the node/bash binary path manually in the params`

The shortcut I input as the first argument (`cmd-alt-opt-u` etc) appears in BTT but doesn't have any actions associated with it. It's just the keyboard command.

I've been digging into the `AppConfig` and I found the `nodeBinaryPath` option, but when I set that, the app crashes when I try to call `btt.addEventListener`.

Here's the config:
Browser:
```
    const btt = new Btt({
      domain: '127.0.0.1',
      port: 58267,
      protocol: 'http',
      version: '2.687',
      sharedKey: 'yourSharedKey',
      nodeBinaryPath: '/usr/local/bin/node',
      // pass eventServer to use this part of the lib
      eventServer: {
        domain: '127.0.0.1',
        port: 8888,
      },
    });
```

btt-node-server:
```
BTT_DOMAIN=127.0.0.1
BTT_PORT=58267
BTT_PROTOCOL=http
BTT_SHARED_KEY=yourSharedKey
BTT_VERSION=2.687
PORT=8888
```

Any ideas? I can just use the btt library to execute triggers that I've already defined, but I'm just curious why it's not working.

**Comment by Worie** [comment] 2019-01-08 17:40
Hi - thanks for reaching out! Glad you're finding it useful in any way!

I'll try to reproduce the issue that you mentioned here, but I'll just need a version of both `btt` and `btt-node-server` packages that you're using :)

**Comment by warrenmcquinn** [comment] 2019-01-08 17:42
Wow quick response! Thanks Worie, good to meet you 😄

Latest releases for both packages - `btt@3.4.0`, `btt-node-server@1.0.0`

**Comment by Worie** [comment] 2019-01-08 17:43
Alright, thanks - and good to meet you too! I'll see what might me an issue and I'll let you know in a bit :)

**Comment by Worie** [comment] 2019-01-08 17:58
Could you provide the snippet of the code that contains `btt.addEventListener`? I mean full method, with all parameters provided (callback function). If the shortcut appears in BTT then the config is probably correct, but lack of any actions assigned to it may be some bigger issue on my part.

Also remember to check if you can "unfold" to see assigned actions for created trigger - there probably should be only one or two actions, first one would be `execute script` that'll send request to `btt-node-server`, second one would be an apple script that shows a notification.

**Comment by warrenmcquinn** [comment] 2019-01-09 15:52
Hey there - I just used some of the example snippets from the `btt` README:

```
// adds real event listener, that'll run once event occurs
btt.addEventListener('cmd+ctrl+alt+u', async (ev) => {
  // write the code as you'd normally do -> trigger the action for some interval
  const intervalID = setInterval(() => {
    btt.showHUD({ title: 'It works!'}).invoke();
  }, 1000);

  // you can use fetch API here or anything that your node version will support

  // stops the interval after 10 seconds
  await new Promise((res, rej) => {
    setTimeout(() => {
      clearTimeout(intervalID);
      res();
    }, 10000);
  });
  
  // the value you return from the callback will be the response of the btt-node-server 
  return { messsage: 'Hello world!' };
});
```

**Comment by Worie** [comment] 2019-01-09 22:16
Hmm, everything seems to be working on my end... Is there any other kind of info that you could provide? For example, could you copy-paste the json of the action that's created after running the script? The empty one that you mentioned to have no actions assigned to them. You can simply press `cmd+c` and paste it here.

That's all I need (probably) to try to reproduce it - so far, It seems to work on my end :(

**Comment by Worie** [comment] 2019-02-13 16:58
Closing for now

**Closed by Worie** 2019-02-13 16:58 UTC
